controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    {}


joint_velocity_controller:
  ros__parameters:

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6


    command_interfaces:
      - velocity


    state_interfaces:
      - position
      - velocity


cartesian_motion_controller:
  ros__parameters:
    robot_base_link: "base_link"
    end_effector_link: "end_effector_link"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - velocity
    solver:
      error_scale: 1.0
      iterations: 20
      publish_state_feedback: True

    pd_gains:
      trans_x: {p: 25.0}
      trans_y: {p: 25.0}
      trans_z: {p: 25.0}
      rot_x: {p: 25.0}
      rot_y: {p: 25.0}
      rot_z: {p: 25.0}


motion_control_handle:
  ros__parameters:
    robot_base_link: "base_link"
    end_effector_link: "end_effector_link"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_1:
        goal: 0.001
      joint_2:
        goal: 0.001
      joint_3:
        goal: 0.001
      joint_4:
        goal: 0.001
      joint_5:
        goal: 0.001
      joint_6:
        goal: 0.001
        
    gains:
      joint_1:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0
      joint_2:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0
      joint_3:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0
      joint_4:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0
      joint_5:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0
      joint_6:
        p: 3.0
        i: 0.0
        i_clamp: 0.0
        d: 0.3
        ff_velocity_scale: 0.0